# Getting Started {-}

## Tools You'll Need {-}

### Excel {-}

#### Using functions {-}

Functions in Excel always begin with an `=` sign. 


### R {-}

R is a programming language  

To get started with R you must first download the base R system onto your computer. By itself, this provides a rudimentary console for interacting with the R programming language. For a more user-friendly experience, download the R Studio integrated development environment (IDE). 

- R can be downloaded [here](https://cran.csiro.au)
- R Studio can be downloaded [here](https://rstudio.com)

In this unit you will largely be dealing with two kind of 'R files': script files and project files.


### Unzipping files {-}

Many of the module resources found in this workbook are downloaded as 'zipped' (i.e. compressed) files. 'Unzipping' (i.e. extracting) these files is simple. 

On MacOS, simply double click the 'zipped' file:
<center>
<video width="768" height="433" controls>
  <source src="images/01-gettingstarted/video1.mp4" type="video/mp4">
</video>
</center>
<br>

On Windows,