# Getting Started {#GettingStarted -}

<h2>Tools You'll Need</h2>

### Visual Studio Code {-} 

Visual Studio Code (VSC) is a text editor that is also a convenient way to view and organise your files. VSC has extensions for other programs that you will use use in this unit, such as RStudio, python and Copilot.


### Excel {-} 

Excel is available on all computer laboratory PC's and can be freely downloaded to personal devices [here](http://portal.office.com). You should already feel confident using Excel from your previous units, however if you need further guidance please visit UWA's resources:

- [Getting started with Excel](https://www.linkedin.com/learning/excel-essential-training-office-365-microsoft-365)
- [Using formulas and functions in Excel](https://www.linkedin.com/learning/excel-advanced-formulas-and-functions)

### R {-}

To get started with R, first download the base R system onto your computer. By itself, this provides a rudimentary console for interacting with the R programming language. For a more user-friendly experience, download the R Studio integrated development environment (IDE). 

- R can be downloaded [here](https://cran.csiro.au)
- R Studio can be downloaded [here](https://www.rstudio.com/products/rstudio/download/#download)

#### Terminology {-}

**File types** 

In this unit you will largely be dealing with two kinds of 'R files': 

- R script files (e.g. `Equations.R`) and,
- R project files (e.g. `Module2Biogeochem.Rproj`) 

R scripts are the raw instructions that tell the R programming language what to do. Meanwhile, an R Project file simply creates an independent workplace environment for you to interact with and manage your scripts. It's wise to create a new R Project file whenever you start working on a new project. 

**Functions and packages**

Just like Excel, you can interact with your data using a variety of *functions* in R. Functions are the tools you use to get the job done. For example, the `plot()` function can be used to create graphs. R is an open source programming language, meaning anyone can create their own functions and bundle them up in a collection known as a *package*. 

**Comments**

All programming languages allow the user to write comments on their code to assist in readability and structure. In R, a comment is defined as a line beginning with a `#`. Any characters written after the `#` are ignored by R and not executed. It's good practice to get into the habit of commenting your R code as it will likely save you (or someone else!) a lot of time later down the track. 

```{r eval=FALSE}
# This is a comment!
library(tidyverse) # You can load packages with the library() function

# Inspect your data with the head() function
head(iris)

# Create a graph using the ggplot() function
ggplot(data = iris, mapping = aes(x = Petal.Length, y = Petal.Width, colour = Species)) +
  geom_point() +
  theme_light()

```


```{block2, hint0, type='rmdtip2'}
To comment multiple lines of code at once in R Studio, press`Command + Shift + C`on MacOS or`Control + Shift + C`on Windows
```


**Further R resources**

If you want to learn more about R and the tidyverse packages, we recommend reading the following (free) textbooks:

- [R for Data Science](https://r4ds.had.co.nz)
- [ggplot2: elegant graphics for data analysis](https://ggplot2-book.org)

### Unzipping files {-}

Many of the module resources found in this workbook are downloaded as 'zipped' (i.e. compressed) files. 'Unzipping' (i.e. extracting) these files is simple. 

On MacOS, simply double click the 'zipped' file:
<center>
<video width="100%" height="100%" controls>
  <source src="images/gettingstarted/video1.mp4" type="video/mp4">
</video>
</center>
<br>

On Windows, click 'Extract All' and follow the prompt:

<center>
<video width="100%" height="100%" controls>
  <source src="images/gettingstarted/video2.mp4" type="video/mp4">
</video>
</center>
<br>


### Installing python {-}

If you do not already have python3 installed, install it. Your mac might already have python2, but you should install python3. 

Go to the website and download the installer.

https://www.python.org/downloads/

Save it anywhere on your computer. Open the installer and choose 'Customize Installation', accept the defaults and click 'Next', then select the folder where you would like to install the program. Don't install it on a network drive or Dropbox folder or some other place prone to failure.

### Setting up the chatbot {-}

One way to access Microsoft Copilot is through Github. Copilot is a chatbot interface that accesses AI programs such as GPT, Claude and Gemini. If you sign up for [Github](https://github.com/education/students) and verify that you are a student, you should get access to Github Pro and Copilot. 
Go to Github and sign up for a student version of Github Pro. 