--- 
title: "Environmental Dynamics Workbook"
author: "Matt Hipsey, Dan Paraska, Alanna Kursar, Giles Knight"
date: "Last updated: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:  ["references/references.bib"]
biblio-style: apalike
link-citations: yes
description: "The online Environmental Dynamics Workbook"
---
# (PART)  Overview {-} 

# Introduction {#intro -}

```{r xaringanExtra, include = FALSE}
library(xaringanExtra)
xaringanExtra::use_panelset()
xaringanExtra::style_panelset_tabs(font_family = "inherit")
```

Welcome to the Environmental Dynamics Workbook! This workbook supplements the practical component of the Environmental Dynamics unit and is designed to develop your ability to model environmental systems. 

Each practical class has a corresponding module that will be added to the workbook as the semester progresses. If you are at all unfamiliar with using Excel or R, please visit the [Getting Started](#GettingStarted) section of this workbook before commencing the first module. 

Please contact your Unit Coordinator or tutor for queries relating to this workbook, or refer to the Unit Outline on LMS for matters relating to the unit's structure. 

#### Contents {-}

1) [Introduction](#intro)
2) [Getting started](#GettingStarted)
3) [Module 1 - Modelling in Excel](#M1_1)
4) [Module 2 - Biogeochemistry](#M2_1)
5) [Module 3 - Climate Modeling](#M3_1)
6) [Module 4 - Oceanic Acidification](#M4_1)
7) [Module 5a - Catchment Water Balance](#M5A_1)
8) [Module 5b - Land Use and Nutrient Management]({#M5B_1)
9) [Module 6 - River Pollution](#M6_1)
10) [Module 7 - Lake Ecosystem Dynamics](#M7_1)
11) [References](#references)