# Module 9: Lake Ecosystem Dynamics {#M9_1 .unnumbered}

### Objectives {#M9_2 .unnumbered}

To use the GLM model to investigate water quality modelling in lakes and to incorporate a coupled hydrodynamic-biogeochemical model.

### Before you start {#M9_before_start -}

- Review modelling aquatic systems lecture

### Module Resources {#M9_3 .unnumbered}

This week, you'll be working through the [**GLM Workbook**](https://aquaticecodynamics.github.io/glm-workbook/). If you're not already familiar with GLM, start by reading the [Setup](https://aquaticecodynamics.github.io/glm-workbook/setup.html), [File Structure](https://aquaticecodynamics.github.io/glm-workbook/glm-file-structure.html), and [Running GLM](https://aquaticecodynamics.github.io/glm-workbook/running-glm.html) chapters.

Your task will be to complete the first portion of the Case Study Exercises, from [Exercise 1: Water Level & Balance](https://aquaticecodynamics.github.io/glm-workbook/WaterBalance.html) up to and including [Exercise 6: Sensitivity Index (SI)](https://aquaticecodynamics.github.io/glm-workbook/sensitivity-index-si.html), as applied to the **WarmLake** case study. The optional phytoplankton section at the end of Exercise 6 is not required.

```{block2, hintM9_1, type='rmdtip2'}
Exercises 7 onwards (Warming Air Scenario, Changing Morphometry and the GLM + Python bonus exercise) are not required this week, but you may find them useful for your final project.
```

### Submission {#M9_13 .unnumbered}

::: {.redbox2}
**Submit properly formatted graphs and tables of the following sections of the lab:**

Water Level & Balance (Exercise 1):

-   Hand drawn diagram of the lake and any variables you used
-   Plots of the water balance using Excel

Water Heating & Stratification (Exercise 2):

-   Plots of the heat fluxes using Excel
-   Plots of the temperature at different layers using Excel

Updating Initial Height Conditions (Exercise 3):

-   Plots of the shallower lake using Excel

Error Assessment (Exercise 4):

-   Temperature error assessment

Adding Water Quality Models (Exercise 5):

-   Hand drawn diagram of the lake with any variables you used
-   Interesting plot of the selected variables

Sensitivity Index (Exercise 6):

-   Temperature sensitivity assessment
-   Tables for submission

These are to be uploaded as per the formatting specified in the [Style Guide](#StyleGuide). Marks will be deducted for incorrect formatting.
<!--
These are to be uploaded in a word doc or PDF format. No screenshots of figures from Excel/Excel spreadsheets to be uploaded

**General professional formatting guidelines:**

-   All figures are to have adequate captions explaining them
-   For graphs, figure captions go below the plot
-   For tables, the caption goes above the table
-   Make sure figures and their text size is readable

**Excel hints:**

-   When there is a caption for a plot, you remove the title
-   Remove the plot border and gridlines
-   Make sure both axes have visible lines and tick marks
-   Units need to be noted properly with the axis label - 'Temperature (°C)'
-   Round numbers to be reasonable
-->
:::
