on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc and gdal dependencies
        run: |
          sudo apt-get install -y pandoc
          sudo apt-get install -y pandoc-citeproc
          sudo apt-get install gdal-bin proj-bin libgdal-dev libproj-dev
          
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
           echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e  'renv::activate()'
          R -e 'renv::restore()'
          
      - name: Get R and OS version
        id: get-version
        run: |
           cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
           cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}    
         
      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
           restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
           
      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Commit automatic build
        run: |
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
           git add docs
           git commit docs -m 'Automatic build' || echo "No changes"
           git push origin || echo "No changes to commit"
